name: Lukh
analytics: {}
content_rating:
  adult: false
github: true
opengraph: {}
title: the paper ink
author:
  name: lukh
color:
  lightness: 0.18944654338747416
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  saturation: 0.0632505684772624
  brandStrength: 0.14257312033851005
  rhythmicContrast: 0.8384284886621005
